version: "3.9"
services:
  backend:
    container_name: hdflex-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32600:80"
    depends_on:
      - "mysql"
      - "mongodb"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/srv/hdflex.tv:delegate
    networks:
      - hdflex-network

  mysql:
    container_name: hdflex-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hdflex
    ports:
        - "32602:3306"
    volumes:
      - ./storage/db/mysql:/var/lib/mysql
    networks:
      - hdflex-network

  mongodb:
    container_name: hdflex-mdb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "32601:27017"
    restart: unless-stopped
    volumes:
      - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./storage/db/mdb:/data/db
    networks:
      - hdflex-network
        
networks:
  hdflex-network:
    external: true