CREATE TABLE IF NOT EXISTS `countries`
(
    `id`         int(11)      NOT NULL AUTO_INCREMENT,
    `code`      varchar(2)   NOT NULL,
    `title`      varchar(255) NOT NULL,
    `en_title`   varchar(255) NULL,
    `created_at` datetime     DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8
  AUTO_INCREMENT = 1;

INSERT INTO `countries` (`code`,`en_title`, `title`)
VALUES
    ('AD','Andorra','Андорра'),
    ('AE','United Arab Emirates','ОАЭ'),
    ('AF','Afghanistan','Афганистан'),
    ('AG','Antigua and Barbuda','Антигуа и Барбуда'),
    ('AI','Anguilla','Ангилья'),
    ('AL','Albania','Албания'),
    ('AM','Armenia','Армения'),
    ('AN','Netherlands Antilles','Нидерландские Антильские о-ва'),
    ('AO','Angola','Ангола'),
    ('AQ','Antarctica','Антарктида'),
    ('AR','Argentina','Аргентина'),
    ('AS','American Samoa','Американское Самоа'),
    ('AT','Austria','Австрия'),
    ('AU','Australia','Австралия'),
    ('AW','Aruba','Аруба'),
    ('AZ','Azerbaijan','Азербайджан'),
    ('BA','Bosnia and Herzegovina','Босния и Герцеговина'),
    ('BB','Barbados','Барбадос'),
    ('BD','Bangladesh','Бангладеш'),
    ('BE','Belgium','Бельгия'),
    ('BF','Burkina Faso','Буркина-Фасо'),
    ('BG','Bulgaria','Болгария'),
    ('BH','Bahrain','Бахрейн'),
    ('BI','Burundi','Бурунди'),
    ('BJ','Benin','Бенин'),
    ('BM','Bermuda','Бермудские о-ва'),
    ('BN','Brunei Darussalam','Бруней-Даруссалам'),
    ('BO','Bolivia','Боливия'),
    ('BR','Brazil','Бразилия'),
    ('BS','Bahamas','Багамские о-ва'),
    ('BT','Bhutan','Бутан'),
    ('BU','Burma','Burma'),
    ('BV','Bouvet Island','о-в Буве'),
    ('BW','Botswana','Ботсвана'),
    ('BY','Belarus','Беларусь'),
    ('BZ','Belize','Белиз'),
    ('CA','Canada','Канада'),
    ('CC','Cocos  Islands','Кокосовые о-ва'),
    ('CD','Congo','Конго - Киншаса'),
    ('CF','Central African Republic','ЦАР'),
    ('CG','Congo','Конго - Браззавиль'),
    ('CH','Switzerland','Швейцария'),
    ('CI','Cote D''Ivoire','Кот-д’Ивуар'),
    ('CK','Cook Islands','о-ва Кука'),
    ('CL','Chile','Чили'),
    ('CM','Cameroon','Камерун'),
    ('CN','China','Китай'),
    ('CO','Colombia','Колумбия'),
    ('CR','Costa Rica','Коста-Рика'),
    ('CS','Serbia and Montenegro','Serbia and Montenegro'),
    ('CU','Cuba','Куба'),
    ('CV','Cape Verde','Кабо-Верде'),
    ('CX','Christmas Island','о-в Рождества'),
    ('CY','Cyprus','Кипр'),
    ('CZ','Czech Republic','Чехия'),
    ('DE','Germany','Германия'),
    ('DJ','Djibouti','Джибути'),
    ('DK','Denmark','Дания'),
    ('DM','Dominica','Доминика'),
    ('DO','Dominican Republic','Доминиканская Республика'),
    ('DZ','Algeria','Алжир'),
    ('EC','Ecuador','Эквадор'),
    ('EE','Estonia','Эстония'),
    ('EG','Egypt','Египет'),
    ('EH','Western Sahara','Западная Сахара'),
    ('ER','Eritrea','Эритрея'),
    ('ES','Spain','Испания'),
    ('ET','Ethiopia','Эфиопия'),
    ('FI','Finland','Финляндия'),
    ('FJ','Fiji','Фиджи'),
    ('FK','Falkland Islands','Фолклендские о-ва'),
    ('FM','Micronesia','Федеративные Штаты Микронезии'),
    ('FO','Faeroe Islands','Фарерские о-ва'),
    ('FR','France','Франция'),
    ('GA','Gabon','Габон'),
    ('GB','United Kingdom','Великобритания'),
    ('GD','Grenada','Гренада'),
    ('GE','Georgia','Грузия'),
    ('GF','French Guiana','Французская Гвиана'),
    ('GH','Ghana','Гана'),
    ('GI','Gibraltar','Гибралтар'),
    ('GL','Greenland','Гренландия'),
    ('GM','Gambia','Гамбия'),
    ('GN','Guinea','Гвинея'),
    ('GP','Guadaloupe','Гваделупа'),
    ('GQ','Equatorial Guinea','Экваториальная Гвинея'),
    ('GR','Greece','Греция'),
    ('GS','South Georgia and the South Sandwich Islands','Южная Георгия и Южные Сандвичевы о-ва'),
    ('GT','Guatemala','Гватемала'),
    ('GU','Guam','Гуам'),
    ('GW','Guinea-Bissau','Гвинея-Бисау'),
    ('GY','Guyana','Гайана'),
    ('HK','Hong Kong','Гонконг (особый район)'),
    ('HM','Heard and McDonald Islands','о-ва Херд и Макдональд'),
    ('HN','Honduras','Гондурас'),
    ('HR','Croatia','Хорватия'),
    ('HT','Haiti','Гаити'),
    ('HU','Hungary','Венгрия'),
    ('ID','Indonesia','Индонезия'),
    ('IE','Ireland','Ирландия'),
    ('IL','Israel','Израиль'),
    ('IN','India','Индия'),
    ('IO','British Indian Ocean Territory','Британская территория в Индийском океане'),
    ('IQ','Iraq','Ирак'),
    ('IR','Iran','Иран'),
    ('IS','Iceland','Исландия'),
    ('IT','Italy','Италия'),
    ('JM','Jamaica','Ямайка'),
    ('JO','Jordan','Иордания'),
    ('JP','Japan','Япония'),
    ('KE','Kenya','Кения'),
    ('KG','Kyrgyz Republic','Киргизия'),
    ('KH','Cambodia','Камбоджа'),
    ('KI','Kiribati','Кирибати'),
    ('KM','Comoros','Коморские о-ва'),
    ('KN','St. Kitts and Nevis','Сент-Китс и Невис'),
    ('KP','North Korea','КНДР'),
    ('KR','South Korea','Республика Корея'),
    ('KW','Kuwait','Кувейт'),
    ('KY','Cayman Islands','Каймановы о-ва'),
    ('KZ','Kazakhstan','Казахстан'),
    ('LA','Lao People''s Democratic Republic','Лаос'),
    ('LB','Lebanon','Ливан'),
    ('LC','St. Lucia','Сент-Люсия'),
    ('LI','Liechtenstein','Лихтенштейн'),
    ('LK','Sri Lanka','Шри-Ланка'),
    ('LR','Liberia','Либерия'),
    ('LS','Lesotho','Лесото'),
    ('LT','Lithuania','Литва'),
    ('LU','Luxembourg','Люксембург'),
    ('LV','Latvia','Латвия'),
    ('LY','Libyan Arab Jamahiriya','Ливия'),
    ('MA','Morocco','Марокко'),
    ('MC','Monaco','Монако'),
    ('MD','Moldova','Молдова'),
    ('ME','Montenegro','Черногория'),
    ('MG','Madagascar','Мадагаскар'),
    ('MH','Marshall Islands','Маршалловы о-ва'),
    ('MK','Macedonia','Македония'),
    ('ML','Mali','Мали'),
    ('MM','Myanmar','Мьянма (Бирма)'),
    ('MN','Mongolia','Монголия'),
    ('MO','Macao','Макао (особый район)'),
    ('MP','Northern Mariana Islands','Северные Марианские о-ва'),
    ('MQ','Martinique','Мартиника'),
    ('MR','Mauritania','Мавритания'),
    ('MS','Montserrat','Монтсеррат'),
    ('MT','Malta','Мальта'),
    ('MU','Mauritius','Маврикий'),
    ('MV','Maldives','Мальдивские о-ва'),
    ('MW','Malawi','Малави'),
    ('MX','Mexico','Мексика'),
    ('MY','Malaysia','Малайзия'),
    ('MZ','Mozambique','Мозамбик'),
    ('NA','Namibia','Намибия'),
    ('NC','New Caledonia','Новая Каледония'),
    ('NE','Niger','Нигер'),
    ('NF','Norfolk Island','о-в Норфолк'),
    ('NG','Nigeria','Нигерия'),
    ('NI','Nicaragua','Никарагуа'),
    ('NL','Netherlands','Нидерланды'),
    ('NO','Norway','Норвегия'),
    ('NP','Nepal','Непал'),
    ('NR','Nauru','Науру'),
    ('NU','Niue','Ниуэ'),
    ('NZ','New Zealand','Новая Зеландия'),
    ('OM','Oman','Оман'),
    ('PA','Panama','Панама'),
    ('PE','Peru','Перу'),
    ('PF','French Polynesia','Французская Полинезия'),
    ('PG','Papua New Guinea','Папуа – Новая Гвинея'),
    ('PH','Philippines','Филиппины'),
    ('PK','Pakistan','Пакистан'),
    ('PL','Poland','Польша'),
    ('PM','St. Pierre and Miquelon','Сен-Пьер и Микелон'),
    ('PN','Pitcairn Island','Питкэрн'),
    ('PR','Puerto Rico','Пуэрто-Рико'),
    ('PS','Palestinian Territory','Палестинские территории'),
    ('PT','Portugal','Португалия'),
    ('PW','Palau','Палау'),
    ('PY','Paraguay','Парагвай'),
    ('QA','Qatar','Катар'),
    ('RE','Reunion','Реюньон'),
    ('RO','Romania','Румыния'),
    ('RS','Serbia','Сербия'),
    ('RU','Russia','Россия'),
    ('RW','Rwanda','Руанда'),
    ('SA','Saudi Arabia','Саудовская Аравия'),
    ('SB','Solomon Islands','Соломоновы о-ва'),
    ('SC','Seychelles','Сейшельские о-ва'),
    ('SD','Sudan','Судан'),
    ('SE','Sweden','Швеция'),
    ('SG','Singapore','Сингапур'),
    ('SH','St. Helena','О-в Св. Елены'),
    ('SI','Slovenia','Словения'),
    ('SJ','Svalbard & Jan Mayen Islands','Шпицберген и Ян-Майен'),
    ('SK','Slovakia','Словакия'),
    ('SL','Sierra Leone','Сьерра-Леоне'),
    ('SM','San Marino','Сан-Марино'),
    ('SN','Senegal','Сенегал'),
    ('SO','Somalia','Сомали'),
    ('SR','Suriname','Суринам'),
    ('SS','South Sudan','Южный Судан'),
    ('ST','Sao Tome and Principe','Сан-Томе и Принсипи'),
    ('SU','Soviet Union','Soviet Union'),
    ('SV','El Salvador','Сальвадор'),
    ('SY','Syrian Arab Republic','Сирия'),
    ('SZ','Swaziland','Свазиленд'),
    ('TC','Turks and Caicos Islands','О-ва Тёркс и Кайкос'),
    ('TD','Chad','Чад'),
    ('TF','French Southern Territories','Французские Южные Территории'),
    ('TG','Togo','Того'),
    ('TH','Thailand','Таиланд'),
    ('TJ','Tajikistan','Таджикистан'),
    ('TK','Tokelau','Токелау'),
    ('TL','Timor-Leste','Восточный Тимор'),
    ('TM','Turkmenistan','Туркменистан'),
    ('TN','Tunisia','Тунис'),
    ('TO','Tonga','Тонга'),
    ('TP','East Timor','East Timor'),
    ('TR','Turkey','Турция'),
    ('TT','Trinidad and Tobago','Тринидад и Тобаго'),
    ('TV','Tuvalu','Тувалу'),
    ('TW','Taiwan','Тайвань'),
    ('TZ','Tanzania','Танзания'),
    ('UA','Ukraine','Украина'),
    ('UG','Uganda','Уганда'),
    ('UM','United States Minor Outlying Islands','Внешние малые о-ва (США)'),
    ('US','United States of America','США'),
    ('UY','Uruguay','Уругвай'),
    ('UZ','Uzbekistan','Узбекистан'),
    ('VA','Holy See','Ватикан'),
    ('VC','St. Vincent and the Grenadines','Сент-Винсент и Гренадины'),
    ('VE','Venezuela','Венесуэла'),
    ('VG','British Virgin Islands','Виргинские о-ва (Британские)'),
    ('VI','US Virgin Islands','Виргинские о-ва (США)'),
    ('VN','Vietnam','Вьетнам'),
    ('VU','Vanuatu','Вануату'),
    ('WF','Wallis and Futuna Islands','Уоллис и Футуна'),
    ('WS','Samoa','Самоа'),
    ('XC','Czechoslovakia','Czechoslovakia'),
    ('XG','East Germany','East Germany'),
    ('XI','Northern Ireland','Northern Ireland'),
    ('XK','Kosovo','Косово'),
    ('YE','Yemen','Йемен'),
    ('YT','Mayotte','Майотта'),
    ('YU','Yugoslavia','Yugoslavia'),
    ('ZA','South Africa','ЮАР'),
    ('ZM','Zambia','Замбия'),
    ('ZR','Zaire','Zaire'),
    ('ZW','Zimbabwe','Зимбабве');
