CREATE TABLE `contents` (
    `id`         INT(11) NOT NULL AUTO_INCREMENT,
    `cdnmovies_id` VARCHAR(64) NULL,
    `ru_title`   VARCHAR(255) NULL,
    `orig_title` VARCHAR(255) NULL,
    `en_title`   VARCHAR(255) NULL,
    `url`      VARCHAR(255) NULL,
    `popularity` FLOAT(8,2) NOT NULL DEFAULT 0,
    `slogan`    VARCHAR(255) NULL,
    `description` TEXT NULL,
    `duration`  INT(11) NOT NULL,
    `iframe_url` VARCHAR(255) NOT NULL,
    `content_type` tinyint(1) NOT NULL DEFAULT 0,
    `year`      INT(11) NOT NULL,
    `poster`   VARCHAR(255) NULL,
    `backdrop` VARCHAR(255) NULL,
    `rating_age` INT(2) NULL,
    `rating_mpaa` VARCHAR(24) NULL,
    `world_premiere` DATE NULL,
    `ru_premiere` DATE NULL,
    `lgbt` tinyint(1) NOT NULL DEFAULT 0,
    `last_season` int(4) NOT NULL DEFAULT 0,
    `last_episode` int(4) NOT NULL DEFAULT 0,
    `last_watch_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;