CREATE TABLE IF NOT EXISTS `genres` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `cdnmovies_id` int(11) NOT NULL,
    `title` varchar(255) NOT NULL,
    `en_title` varchar(255) NULL,
    `created_at` datetime     DEFAULT CURRENT_TIMESTAMP,
    `updated_at` datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

INSERT INTO `genres` (`cdnmovies_id`,`title`,`en_title`)
VALUES
    (1,'триллер','triller'),
    (2,'драма','drama'),
    (3,'криминал','crime'),
    (4,'детектив','detective'),
    (5,'биография','biography'),
    (6,'вестерн','western'),
    (7,'ужасы','horrors'),
    (8,'комедия','comedy'),
    (9,'мелодрама','melodrama'),
    (10,'история','history'),
    (11,'боевик','action movie'),
    (12,'фантастика','fantastic'),
    (13,'приключения','adventures'),
    (14,'фэнтези','fantasy'),
    (15,'мультфильм','cartoon'),
    (16,'семейный','family'),
    (17,'военный','military'),
    (18,'музыка','music'),
    (19,'аниме','anime'),
    (20,'детский','childlike'),
    (21,'короткометражка','short film'),
    (22,'игра','game'),
    (23,'мюзикл','musical'),
    (24,'спорт','sport'),
    (25,'документальный','documentary'),
    (26,'реальное ТВ','real TV'),
    (27,'фильм-нуар','film noir'),
    (28,'ток-шоу','talk shows'),
    (29,'концерт','concert'),
    (30,'для взрослых','for adults'),
    (31,'новости','news'),
    (32,'мистика','mistic'),
    (33,'эротика','erotic'),
    (34,'арт-хаус','art-house'),
    (35,'путешествия','travels');
